# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

dist: goreleaser-dist

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild

brews:
  - name: cargo-bumpversion
    ids:
      - cargo-bumpversion
    description: "Plugin for `cargo` to update all version strings in your project and optionally commit and tag the changes"
    directory: Formula
    commit_author:
      name: romnn
      email: contact@romnn.com
    repository:
      owner: romnn
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: false
  - name: bumpversion
    ids:
      - bumpversion
    description: "Update all version strings in your project and optionally commit and tag the changes"
    directory: Formula
    commit_author:
      name: romnn
      email: contact@romnn.com
    repository:
      owner: romnn
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: false

builds:
  # cargo-bumpversion binary
  - id: "cargo-bumpversion"
    builder: rust
    binary: cargo-bumpversion
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    dir: ./
    tool: cargo
    command: zigbuild
    flags:
      - "--release"
      - "--package=cargo-bumpversion"
      - "--bin=cargo-bumpversion"
      - "--target-dir=./target" # TODO: can we remove this once rust support is better?

  # bumpversion binary
  - id: "bumpversion"
    builder: rust
    binary: bumpversion
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    dir: ./
    tool: cargo
    command: zigbuild
    flags:
      - "--release"
      - "--package=cargo-bumpversion"
      - "--bin=bumpversion"
      - "--target-dir=./target" # TODO: can we remove this once rust support is better?

archives:
  - id: cargo-bumpversion
    formats: ["tar.gz"]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - cargo-bumpversion
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        formats: ["zip"]
  - id: bumpversion
    formats: ["tar.gz"]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - bumpversion
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  filters:
    exclude:
      - "^ci:"
      - "^docs:"
      - "^test:"

release:
  draft: false
