[workspace]
resolver = "2"
members = [
  "lib",
  "bin/bumpversion",
  "crates/serde-ini-spanned",
  # "crates/serde-ini",
  # "bin/cargo-bumpversion",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["romnn <contact@romnn.com>"]
license-file = "LICENSE"
documentation = "https://docs.rs/cargo-bumpversion"
homepage = "https://github.com/romnn/cargo-bumpversion"
repository = "https://github.com/romnn/cargo-bumpversion"
readme = "README.md"
categories = [
  "command-line-utilities",
]
keywords = [
  "semver",
  "bumpversion",
  "bump2version",
]
exclude = []

[profile.release]
lto = true
codegen-units = 1

[workspace.dependencies]
thiserror = "2"
color-eyre = "0"
tracing = "0"
once_cell = "1"

bumpversion = { path = "./lib" }
