[package]
name = "cargo-bumpversion-cli"
publish = false
description = "cargo plugin to bump semver version in your project"
readme = "README.md"
exclude = []

version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[[bin]]
name = "cargo-bumpversion"
path = "src/main.rs"

[dependencies]
color-eyre.workspace = true
clap.workspace = true
common.workspace = true
bumpversion.workspace = true
