[package]
name = "bumpversion-cli"
publish = false
description = "bump semver version in your project"
readme = "README.md"
default-run = "bumpversion"
exclude = []

version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[[bin]]
name = "bumpversion"
path = "src/bumpversion.rs"

# [[bin]]
# name = "cargo-bumpversion"
# path = "src/cargo_bumpversion.rs"

[package.metadata.cargo-feature-combinations]
denylist = ["default"]

[dependencies]
color-eyre.workspace = true
clap = { version = "4", features = ["derive", "env", "color"] }
clap-verbosity-flag = "2"

# logging
tracing.workspace = true
tracing-subscriber = { version = "0", features = ["json", "env-filter"] }

# colors and diagnostics
atty = "0"
termcolor = "1"
codespan-reporting = "0"

bumpversion.workspace = true
