[package]
name = "common"
publish = false

version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
color-eyre.workspace = true
clap.workspace = true

clap-verbosity-flag = "2"
