name: build

on: [push, pull_request]

jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yaml

  build:
    name: build ${{ matrix.package.name }} (features ${{ matrix.features }})
    runs-on: ubuntu-latest
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.package-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Compile binaries
        run: >-
          cargo build
          --package "${{ matrix.package.name }}"
          --features "${{ matrix.features }}"
          --all-targets
