name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test (features ${{ matrix.features }})
    strategy:
      fail-fast: false
      matrix:
        features: ["", "native", "git2", "git-repository", "all"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Configure git author
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "test"

      - name: Test
        run: >-
          cargo test
          --features "${{ matrix.features }}"
          --all-targets
