name: test

on: [push, pull_request]

jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yml

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Audit
        continue-on-error: true
        run: |
          cargo install cargo-audit
          cargo audit

  test:
    name: test (features ${{ matrix.features }})
    runs-on: ubuntu-latest
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.package-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Configure git author
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "test"

      - name: Test
        run: >-
          cargo test
          --package "${{ matrix.package.name }}"
          --features "${{ matrix.features }}"
          --all-targets
